# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "21c9a318f620e0956ded884ede415cff"
application_url = "https://oorxd-2409-408d-1d8a-c60c-bd43-295f-b2c1-f6e0.free.pinggy.net"
embedded = true
name = "vinupriyaapp"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://oorxd-2409-408d-1d8a-c60c-bd43-295f-b2c1-f6e0.free.pinggy.net/auth.php"
]

[webhooks]
api_version = "2026-07"

[app_proxy]
url = "https://oorxd-2409-408d-1d8a-c60c-bd43-295f-b2c1-f6e0.free.pinggy.net/api/proxy"
subpath = "lms"
prefix = "apps"
